config/routes.rb
Ordi::Application.routes.draw do
  
  resources :user_sessions
  
  resources :users
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout  
    
  resources :karteikarten do
    get 'print', :on => :member
    
    resources :tiere, :only => :new
    
    resources :behandlungen, :only => :destroy
  end
  
  resources :abfragen, :only => :index
  
  root :to => 'karteikarten#index'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]

  def new
    @user = User.new
  end
  
  def create
    if @user = login(params[:username], params[:password])
      flash[:notice] = 'Anmeldung erfolgreich.'
      redirect_to karteikarten_path()
    else
      flash.now[:error] = "Fehler bei Anmeldung."
      render :action => :new
    end
  end
    
  def destroy
    logout
    flash[:notice] = 'Auf wiedersehen!'
    redirect_to login_path()
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <table>
    <tr>
      <td><%= label_tag :Benutzername %></td>
      <td><%= text_field_tag :username %></td>
    </tr>
    <tr>
      <td><%= label_tag :Passwort %></td>
      <td><%= password_field_tag :password %></td>
    </tr>
  </table>
  
  <br>
  <%= submit_tag "anmelden" %>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Ordi Anmeldung</h1>

<%= render 'form' %>