config/routes.rb
Ordi::Application.routes.draw do
  
  resources :user_sessions
  
  resources :users
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout  
    
  resources :karteikarten do
    get 'print', :on => :member
    
    resources :tiere, :only => :new
    
    resources :behandlungen, :only => :destroy
  end
  
  resources :abfragen, :only => :index
  
  root :to => 'karteikarten#index'
end

app/views/layouts/_header.html.erb
<table style="width: 100%">
	<colgroup>
		<col width="50%">
		<col width="20%">
    <col width="20%">
    <col width="10%">
	<colgroup>
			
	<tr style="background-color: RoyalBlue;">
		<td>
      <h1 class="header">
        <%= link_to "Patientenübersicht", karteikarten_path(), :class => current_page?(karteikarten_path()) ? "current" : "header" %> &nbsp;&nbsp;  
		    <%= link_to "Abfragen", abfragen_path(), :class => current_page?(abfragen_path()) ? "current" : "header" %>
      </h1>
    </td>
    <td>
      <%#= yield :header %>
    </td>
    <td>
      <% if signed_in? %>
        <h1 style="color: #FBFBB1; font-weight: normal" class="header">Willkommen <%= current_user.username %></h1>
      <% end %>
    </td>
		<td style="text-align: right">
      <% if signed_in? %>
        <h1 class="header"><%= link_to "abmelden", logout_path(), :method => :delete, :class => current_page?(logout_path()) ? "current" : "header" %></h1>
      <% else %>
        <h1 class="header"><%= link_to "anmelden", login_path(), :class => "current" %></h1>
      <% end %>
    </td>
	</tr>
</table>

app/views/layouts/_smarticonbar.html.erb
<div id="smarticonbar">					
  <table cellspacing="0" cellpadding="0" width="100%">
    <colgroup>
      <col width="4%" />
      <col width="4%" />
      <col width="4%" />
      <col width="4%" />
      <col width="80%" />
      <col width="4%" />
    </colgroup>
    <tr> 
      <td><%= link_to( content_tag( 'div', image_tag('home.png'), :title => 'Patientenübersicht' ), { :action => 'index'}, :class => 'text_button'  ) %></td>
	  
	  <td><%= link_to( content_tag( 'div', image_tag('dog.png'), :title => 'Neue Karteikarte' ), { :action => 'new'}, :class => 'text_button'  ) %></td>
	  
	  <td><%= link_to( content_tag( 'div', image_tag('print.png'), :title => 'Drucken' ), { :action => 'print'}, :class => 'text_button'  ) %></td>

      <td><%= link_to( content_tag( 'div', image_tag('search.png'), :title => 'Abfragen' ), abfragen_karteikarten_path(), {:class => 'text_button'}  ) %></td>

      <td></td>
	  
	  <td></td>
    </tr>
  </table>  
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ordi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='application'>
   
    <%= render :partial => 'layouts/header' %>

    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  
    <%= yield %>
</body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ordi HTML Druck</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="print">
  
    <%= yield %>
    
    <script>
       /* 	$(document).ready(function() {
            window.print();
          } );
       */
    </script>
</body>
</html>